### PR TITLE
[TASK] Declare compatible with Flow 3.0

### PR DESCRIPTION
**Pull request by kdambekalns**
Adjusts the composer manifest so the package can be installed with Flow 3.0 as well.

### CODE REVIEW

**Comment by kdambekalns** [comment]
If this is merged, I'd tag the package with 5.4.1

**Comment by kdambekalns** [comment]
@elbebass Let me know if this works for you…

**Comment by aertmann** [comment]
:+1:

**Comment by elbebass** [comment]
@kdambekalns yeah it does

**Pull request merged**
